CREATE TABLE `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL COMMENT '用户id',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(50) NOT NULL,
  `salt` VARCHAR(128) DEFAULT NULL COMMENT '加密盐值',
  `email` VARCHAR(50) DEFAULT NULL COMMENT '邮箱',
  `phone` VARCHAR(50) DEFAULT NULL COMMENT '联系方式',
  `sex` INT(255) DEFAULT NULL COMMENT '年龄：1男2女',
  `age` INT(3) DEFAULT NULL COMMENT '年龄',
  `status` INT(1) NOT NULL COMMENT '用户状态：1有效; 2删除',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  PRIMARY KEY (`id`,`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` VARCHAR(20) NOT NULL COMMENT '角色id',
  `name` VARCHAR(50) NOT NULL COMMENT '角色名称',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '角色描述',
  `status` INT(1) NOT NULL COMMENT '状态：1有效；2删除',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `permission_id` VARCHAR(20) NOT NULL COMMENT '权限id',
  `name` VARCHAR(100) NOT NULL COMMENT '权限名称',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '权限描述',
  `url` VARCHAR(255) DEFAULT NULL COMMENT '权限访问路径',
  `perms` VARCHAR(255) DEFAULT NULL COMMENT '权限标识',
  `parent_id` INT(11) DEFAULT NULL COMMENT '父级权限id',
  `type` INT(1) DEFAULT NULL COMMENT '类型   0：目录   1：菜单   2：按钮',
  `order_num` INT(3) DEFAULT '0' COMMENT '排序',
  `icon` VARCHAR(50) DEFAULT NULL COMMENT '图标',
  `status` INT(1) NOT NULL COMMENT '状态：1有效；2删除',
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(20) NOT NULL COMMENT '用户id',
  `role_id` INT(20) NOT NULL COMMENT '角色id',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `role_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(20) NOT NULL COMMENT '角色id',
  `permission_id` INT(20) NOT NULL COMMENT '权限id',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `user_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(20) NOT NULL COMMENT '角色id',
  `permission_id` INT(20) NOT NULL COMMENT '权限id',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;