# 服务端口号
server:
  port: 8750

#Eureka 相关配置
eureka:
  instance:
    hostname: localhost
  # 关闭自我保护，及时剔除无用服务
  server:
    enableSelfPreservation: false
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false

spring:
  application:
    name: springcloud-wj-eureka
  security:
    user:
      name: admin # 用户密码
      password: admin